apiVersion: v1
kind: Service
metadata:
  name: postgres-main
spec:
  selector:
    app: postgres-main
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP  # This line has been added to restrict access to the service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-script
data:
  00_init.sql: |
    ALTER USER dbuser1 REPLICATION;
    SELECT pg_create_physical_replication_slot('replication_slot');
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-main
spec:
  serviceName: "postgres-main"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-main
  template:
    metadata:
      labels:
        app: postgres-main
    spec:
      containers:
        - name: postgres-main
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tododb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "password\nhost replication all 0.0.0.0/0 md5"
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-host=password"
          command: ["docker-entrypoint.sh"]
          args: ["-c", "wal_level=replica", "-c", "hot_standby=on", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10", "-c", "hot_standby_feedback=on"]
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql/data
            - name: init-sql-script
              mountPath: /docker-entrypoint-initdb.d/00_init.sql
              subPath: 00_init.sql
      volumes:
        - name: init-sql-script
          configMap:
            name: init-sql-script
            items:
              - key: 00_init.sql
                path: 00_init.sql      
  volumeClaimTemplates:
    - metadata:
        name: postgresql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
